baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[outputFormats.RobotsTXT]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true
permalinkable = true

[outputs]
home = ["HTML", "RSS", "RobotsTXT"]

